import { Product, Platform, Category, ProductCondition, PriceScore } from "@/types";

// Platform Logos (using emoji for initial demo, can be replaced with actual logos)
export const PLATFORM_LOGOS: Record<Platform, string> = {
    wallapop: "🛍️",
    vinted: "👚",
    ebay: "🏪",
    milanuncios: "📢",
};

// Mock Product Data (30+ items covering all 13 categories)
export const MOCK_PRODUCTS: Product[] = [
    {
        id: "1",
        title: "iPhone 13 Pro 128GB - Like New",
        description: "Excellent condition, battery health 95%, with original box and charger",
        price: 599.99,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1632661674596-df8be070a5c5?w=500",
        source_url: "https://wallapop.com/item/1",
        platform: "wallapop",
        category: "tech-electronics",
        location: "Madrid, Spain",
        condition: "like-new",
        phash: null,
        price_score: "bargain",
        created_at: new Date("2026-01-15"),
    },
    {
        id: "2",
        title: "Nike Air Max 90 - Size 42",
        description: "Brand new, never worn. Original packaging included.",
        price: 89.99,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500",
        source_url: "https://vinted.com/item/2",
        platform: "vinted",
        category: "fashion",
        location: "Barcelona, Spain",
        condition: "new",
        phash: null,
        price_score: "fair",
        created_at: new Date("2026-01-14"),
    },
    {
        id: "3",
        title: "Mountain Bike Trek X-Caliber 8",
        description: "29-inch wheels, hydraulic disc brakes, used for one season",
        price: 750.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=500",
        source_url: "https://ebay.com/item/3",
        platform: "ebay",
        category: "sports-leisure",
        location: "Valencia, Spain",
        condition: "good",
        phash: null,
        price_score: "bargain",
        created_at: new Date("2026-01-13"),
    },
    {
        id: "4",
        title: "Vintage Leather Sofa - 3 Seater",
        description: "Classic Chesterfield design, genuine Italian leather",
        price: 1200.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500",
        source_url: "https://milanuncios.com/item/4",
        platform: "milanuncios",
        category: "home-garden",
        location: "Seville, Spain",
        condition: "good",
        phash: null,
        price_score: "expensive",
        created_at: new Date("2026-01-12"),
    },
    {
        id: "5",
        title: "Canon EOS R6 Camera Body",
        description: "Full-frame mirrorless, 20MP, 4K video, shutter count: 5000",
        price: 1899.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=500",
        source_url: "https://wallapop.com/item/5",
        platform: "wallapop",
        category: "tech-electronics",
        location: "Madrid, Spain",
        condition: "like-new",
        phash: null,
        price_score: "fair",
        created_at: new Date("2026-01-11"),
    },
    {
        id: "6",
        title: "Zara Wool Coat - Size M",
        description: "Navy blue, barely worn, perfect for winter",
        price: 45.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=500",
        source_url: "https://vinted.com/item/6",
        platform: "vinted",
        category: "fashion",
        location: "Bilbao, Spain",
        condition: "like-new",
        phash: null,
        price_score: "bargain",
        created_at: new Date("2026-01-10"),
    },
    {
        id: "7",
        title: "Harry Potter Complete Collection",
        description: "All 7 books in hardcover, excellent condition",
        price: 65.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf?w=500",
        source_url: "https://ebay.com/item/7",
        platform: "ebay",
        category: "movies-books-music",
        location: "Granada, Spain",
        condition: "good",
        phash: null,
        price_score: "fair",
        created_at: new Date("2026-01-09"),
    },
    {
        id: "8",
        title: "Baby Stroller Bugaboo Fox 2",
        description: "All-terrain stroller, lightweight, adjustable handlebar",
        price: 550.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=500",
        source_url: "https://wallapop.com/item/8",
        platform: "wallapop",
        category: "baby-kids",
        location: "Málaga, Spain",
        condition: "good",
        phash: null,
        price_score: "bargain",
        created_at: new Date("2026-01-08"),
    },
    {
        id: "9",
        title: "Electric Guitar Fender Stratocaster",
        description: "Sunburst finish, maple neck, with hard case",
        price: 899.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1510915228340-29c85a43dcfe?w=500",
        source_url: "https://milanuncios.com/item/9",
        platform: "milanuncios",
        category: "movies-books-music",
        location: "Zaragoza, Spain",
        condition: "good",
        phash: null,
        price_score: "fair",
        created_at: new Date("2026-01-07"),
    },
    {
        id: "10",
        title: "Gaming PC - RTX 3080, Ryzen 7",
        description: "Custom build, 32GB RAM, 1TB NVMe SSD, water-cooled",
        price: 1450.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?w=500",
        source_url: "https://wallapop.com/item/10",
        platform: "wallapop",
        category: "tech-electronics",
        location: "Madrid, Spain",
        condition: "like-new",
        phash: null,
        price_score: "bargain",
        created_at: new Date("2026-01-06"),
    },
    {
        id: "11",
        title: "Adidas Ultraboost Running Shoes",
        description: "Size 41, black colorway, minimal wear",
        price: 75.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=500",
        source_url: "https://vinted.com/item/11",
        platform: "vinted",
        category: "sports-leisure",
        location: "Barcelona, Spain",
        condition: "good",
        phash: null,
        price_score: "fair",
        created_at: new Date("2026-01-05"),
    },
    {
        id: "12",
        title: "Wooden Dining Table + 6 Chairs",
        description: "Solid oak, extends to seat 8, slight wear on table top",
        price: 480.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=500",
        source_url: "https://ebay.com/item/12",
        platform: "ebay",
        category: "home-garden",
        location: "Valencia, Spain",
        condition: "good",
        phash: null,
        price_score: "bargain",
        created_at: new Date("2026-01-04"),
    },
    {
        id: "13",
        title: "MacBook Pro 14 M1 Pro 16GB",
        description: "Space Gray, AppleCare+ until 2027, pristine condition",
        price: 1999.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500",
        source_url: "https://wallapop.com/item/13",
        platform: "wallapop",
        category: "tech-electronics",
        location: "Madrid, Spain",
        condition: "like-new",
        phash: null,
        price_score: "fair",
        created_at: new Date("2026-01-03"),
    },
    {
        id: "14",
        title: "Vintage Vinyl Record Collection",
        description: "50+ records from the 70s-90s, classic rock and jazz",
        price: 250.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=500",
        source_url: "https://milanuncios.com/item/14",
        platform: "milanuncios",
        category: "collectibles-art",
        location: "Seville, Spain",
        condition: "good",
        phash: null,
        price_score: "expensive",
        created_at: new Date("2026-01-02"),
    },
    {
        id: "15",
        title: "DJI Mavic Air 2 Drone",
        description: "4K camera, fly more combo with 3 batteries and carrying case",
        price: 650.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1473968512647-3e447244af8f?w=500",
        source_url: "https://ebay.com/item/15",
        platform: "ebay",
        category: "tech-electronics",
        location: "Barcelona, Spain",
        condition: "like-new",
        phash: null,
        price_score: "bargain",
        created_at: new Date("2026-01-01"),
    },
    {
        id: "16",
        title: "Burberry Trench Coat - Classic",
        description: "Authentic, size 38, beige, timeless design",
        price: 380.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=500",
        source_url: "https://vinted.com/item/16",
        platform: "vinted",
        category: "fashion",
        location: "Madrid, Spain",
        condition: "good",
        phash: null,
        price_score: "fair",
        created_at: new Date("2025-12-31"),
    },
    {
        id: "17",
        title: "Road Bike Specialized Allez",
        description: "Carbon fork, Shimano 105 groupset, 54cm frame",
        price: 590.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=500",
        source_url: "https://wallapop.com/item/17",
        platform: "wallapop",
        category: "sports-leisure",
        location: "Valencia, Spain",
        condition: "good",
        phash: null,
        price_score: "bargain",
        created_at: new Date("2025-12-30"),
    },
    {
        id: "18",
        title: "IKEA KALLAX Shelving Unit (White)",
        description: "4x4 grid, perfect condition, easy to disassemble for pickup",
        price: 45.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1594620302200-9a762244a156?w=500",
        source_url: "https://milanuncios.com/item/18",
        platform: "milanuncios",
        category: "home-garden",
        location: "Bilbao, Spain",
        condition: "like-new",
        phash: null,
        price_score: "fair",
        created_at: new Date("2025-12-29"),
    },
    {
        id: "19",
        title: "PlayStation 5 Digital Edition",
        description: "1 year old, includes 2 controllers and 5 games",
        price: 380.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=500",
        source_url: "https://ebay.com/item/19",
        platform: "ebay",
        category: "tech-electronics",
        location: "Málaga, Spain",
        condition: "good",
        phash: null,
        price_score: "fair",
        created_at: new Date("2025-12-28"),
    },
    {
        id: "20",
        title: "Antique Wooden Cabinet",
        description: "Early 1900s, restored, beautiful carvings, display piece",
        price: 890.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=500",
        source_url: "https://wallapop.com/item/20",
        platform: "wallapop",
        category: "collectibles-art",
        location: "Granada, Spain",
        condition: "good",
        phash: null,
        price_score: "expensive",
        created_at: new Date("2025-12-27"),
    },
    // NEW: Cars & Motorcycles Category
    {
        id: "21",
        title: "BMW 320d 2018 - Diesel",
        description: "150,000 km, full service history, sports package",
        price: 18500.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=500",
        source_url: "https://milanuncios.com/item/21",
        platform: "milanuncios",
        category: "cars-motorcycles",
        location: "Madrid, Spain",
        condition: "good",
        phash: null,
        price_score: "bargain",
        created_at: new Date("2025-12-26"),
    },
    {
        id: "22",
        title: "Yamaha MT-07 Motorcycle 2020",
        description: "Low mileage, one owner, ABS, excellent condition",
        price: 5999.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=500",
        source_url: "https://wallapop.com/item/22",
        platform: "wallapop",
        category: "cars-motorcycles",
        location: "Barcelona, Spain",
        condition: "like-new",
        phash: null,
        price_score: "bargain",
        created_at: new Date("2025-12-25"),
    },
    // NEW: Real Estate Category
    {
        id: "23",
        title: "Studio Apartment - City Center",
        description: "35m², renovated, 5th floor with elevator, near metro",
        price: 145000.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=500",
        source_url: "https://milanuncios.com/item/23",
        platform: "milanuncios",
        category: "real-estate",
        location: "Madrid, Spain",
        condition: "like-new",
        phash: null,
        price_score: "fair",
        created_at: new Date("2025-12-24"),
    },
    {
        id: "24",
        title: "Country House with Land",
        description: "250m² house + 2000m² land, rustic style, mountain views",
        price: 280000.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=500",
        source_url: "https://milanuncios.com/item/24",
        platform: "milanuncios",
        category: "real-estate",
        location: "Ávila, Spain",
        condition: "good",
        phash: null,
        price_score: "bargain",
        created_at: new Date("2025-12-23"),
    },
    // NEW: DIY Category
    {
        id: "25",
        title: "Bosch Professional Drill Set",
        description: "18V cordless drill + impact driver, 2 batteries, charger, case",
        price: 189.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500",
        source_url: "https://ebay.com/item/25",
        platform: "ebay",
        category: "diy",
        location: "Valencia, Spain",
        condition: "like-new",
        phash: null,
        price_score: "bargain",
        created_at: new Date("2025-12-22"),
    },
    {
        id: "26",
        title: "Workbench with Tool Storage",
        description: "Heavy-duty steel frame, wooden top, drawer + cabinet storage",
        price: 220.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=500",
        source_url: "https://wallapop.com/item/26",
        platform: "wallapop",
        category: "diy",
        location: "Seville, Spain",
        condition: "good",
        phash: null,
        price_score: "fair",
        created_at: new Date("2025-12-21"),
    },
    // NEW: Agriculture & Industrial Category
    {
        id: "27",
        title: "John Deere Compact Tractor",
        description: "25HP, 4WD, 500 hours, front loader included",
        price: 12500.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=500",
        source_url: "https://milanuncios.com/item/27",
        platform: "milanuncios",
        category: "agriculture-industrial",
        location: "Salamanca, Spain",
        condition: "good",
        phash: null,
        price_score: "bargain",
        created_at: new Date("2025-12-20"),
    },
    {
        id: "28",
        title: "Industrial Pallet Jack",
        description: "2500kg capacity, hydraulic, excellent working condition",
        price: 350.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=500",
        source_url: "https://wallapop.com/item/28",
        platform: "wallapop",
        category: "agriculture-industrial",
        location: "Zaragoza, Spain",
        condition: "good",
        phash: null,
        price_score: "fair",
        created_at: new Date("2025-12-19"),
    },
    // NEW: Services Category
    {
        id: "29",
        title: "Home Cleaning Service",
        description: "Professional cleaning, flexible hours, eco-friendly products",
        price: 25.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=500",
        source_url: "https://milanuncios.com/item/29",
        platform: "milanuncios",
        category: "services",
        location: "Madrid, Spain",
        condition: "new",
        phash: null,
        price_score: "fair",
        created_at: new Date("2025-12-18"),
    },
    {
        id: "30",
        title: "Private Guitar Lessons",
        description: "Experienced teacher, all levels, at your home or online",
        price: 30.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1564186763535-ebb21ef5277f?w=500",
        source_url: "https://wallapop.com/item/30",
        platform: "wallapop",
        category: "services",
        location: "Barcelona, Spain",
        condition: "new",
        phash: null,
        price_score: "bargain",
        created_at: new Date("2025-12-17"),
    },
    // NEW: Others Category
    {
        id: "31",
        title: "Parking Space - Monthly Rent",
        description: "Covered parking, secure building, 24/7 access",
        price: 80.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=500",
        source_url: "https://milanuncios.com/item/31",
        platform: "milanuncios",
        category: "others",
        location: "Madrid, Spain",
        condition: "new",
        phash: null,
        price_score: "fair",
        created_at: new Date("2025-12-16"),
    },
    {
        id: "32",
        title: "Event Tickets - Music Festival",
        description: "2-day pass, premium camping, June 2026",
        price: 180.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=500",
        source_url: "https://wallapop.com/item/32",
        platform: "wallapop",
        category: "others",
        location: "Valencia, Spain",
        condition: "new",
        phash: null,
        price_score: "bargain",
        created_at: new Date("2025-12-15"),
    },
];
