import { Product, Platform, Category } from "@/types";

// Platform Logos for affiliate partners
export const PLATFORM_LOGOS: Record<Platform, string> = {
    amazon: "🛒",
    etsy: "🎨",
    elcorteingles: "🏬",
    fnac: "📚",
    decathlon: "⚽",
};

// Platform display names
export const PLATFORM_NAMES: Record<Platform, string> = {
    amazon: "Amazon",
    etsy: "Etsy",
    elcorteingles: "El Corte Inglés",
    fnac: "Fnac",
    decathlon: "Decathlon",
};

// Category icons for quiz chips
export const CATEGORY_ICONS: Record<Category, string> = {
    "tech-electronics": "💻",
    "fashion": "👗",
    "sports-outdoors": "🏃",
    "home-garden": "🏠",
    "movies": "🎬",
    "books": "📚",
    "music": "🎵",
    "baby-kids": "👶",
    "collectibles-art": "🎨",
    "diy": "🔧",
    "motor-accessories": "🚗",
    "beauty-personal-care": "💄",
    "travel-experiences": "✈️",
};

// Mock Gift Products for development
export const MOCK_PRODUCTS: Product[] = [
    {
        id: "1",
        title: "Apple AirPods Pro (2ª generación)",
        description: "Cancelación activa de ruido, audio espacial personalizado y resistencia al agua.",
        price: 279.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=500",
        source_url: "https://amazon.es/dp/B0BDHWDR12",
        platform: "amazon",
        category: "tech-electronics",
        findly_reason: "Perfecto para amantes de la música y la tecnología que buscan calidad premium.",
        created_at: new Date("2026-01-15"),
    },
    {
        id: "2",
        title: "Bolso de piel artesanal personalizado",
        description: "Cuero genuino, hecho a mano en España. Personalizable con iniciales.",
        price: 89.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500",
        source_url: "https://etsy.com/listing/123456",
        platform: "etsy",
        category: "fashion",
        findly_reason: "Un regalo único y personalizado que demuestra atención al detalle.",
        created_at: new Date("2026-01-14"),
    },
    {
        id: "3",
        title: "Set de Yoga Premium con Esterilla",
        description: "Incluye esterilla eco-friendly, bloques de corcho y correa de algodón orgánico.",
        price: 59.90,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500",
        source_url: "https://decathlon.es/set-yoga-premium",
        platform: "decathlon",
        category: "sports-outdoors",
        findly_reason: "Ideal para quien busca bienestar y un estilo de vida activo.",
        created_at: new Date("2026-01-13"),
    },
    {
        id: "4",
        title: "Lámpara de diseño nórdico",
        description: "Lámpara de mesa minimalista con base de madera y pantalla de lino.",
        price: 75.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=500",
        source_url: "https://elcorteingles.es/hogar/lamparas",
        platform: "elcorteingles",
        category: "home-garden",
        findly_reason: "El toque perfecto para un hogar acogedor y con estilo.",
        created_at: new Date("2026-01-12"),
    },
    {
        id: "5",
        title: "Colección Harry Potter Edición Especial",
        description: "Los 7 libros en estuche coleccionista con ilustraciones exclusivas.",
        price: 149.99,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf?w=500",
        source_url: "https://fnac.es/harry-potter-coleccion",
        platform: "fnac",
        category: "books",
        findly_reason: "Un tesoro para los fans de la saga mágica más famosa del mundo.",
        created_at: new Date("2026-01-11"),
    },
    {
        id: "6",
        title: "Mochila portabebés ergonómica",
        description: "Diseño ergonómico certificado, múltiples posiciones, tejido transpirable.",
        price: 129.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1522771930-78848d9293e8?w=500",
        source_url: "https://amazon.es/dp/B0BABY123",
        platform: "amazon",
        category: "baby-kids",
        findly_reason: "Comodidad y seguridad para los primeros años de aventuras juntos.",
        created_at: new Date("2026-01-10"),
    },
    {
        id: "7",
        title: "Set de acuarelas profesional",
        description: "48 colores de alta pigmentación con pinceles de pelo natural y papel de algodón.",
        price: 65.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500",
        source_url: "https://amazon.es/dp/B0ART456",
        platform: "amazon",
        category: "collectibles-art",
        findly_reason: "Para el artista que lleva dentro, con materiales de calidad profesional.",
        created_at: new Date("2026-01-09"),
    },
    {
        id: "8",
        title: "Kit de herramientas Bosch profesional",
        description: "Maletín con 108 piezas: taladro, destornilladores, llaves y accesorios.",
        price: 189.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=500",
        source_url: "https://amazon.es/dp/B0BOSCH789",
        platform: "amazon",
        category: "diy",
        findly_reason: "Todo lo necesario para los proyectos de bricolaje más ambiciosos.",
        created_at: new Date("2026-01-08"),
    },
    {
        id: "9",
        title: "Funda de cuero para smartphone",
        description: "Cuero italiano genuino, diseño slim con protección de cámara.",
        price: 45.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=500",
        source_url: "https://etsy.com/listing/789012",
        platform: "etsy",
        category: "motor-accessories",
        findly_reason: "Elegancia y protección para el compañero tecnológico de cada día.",
        created_at: new Date("2026-01-07"),
    },
    {
        id: "10",
        title: "Set skincare coreano premium",
        description: "Rutina completa: limpiador, tónico, sérum, crema y mascarillas.",
        price: 79.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500",
        source_url: "https://elcorteingles.es/belleza/skincare",
        platform: "elcorteingles",
        category: "beauty-personal-care",
        findly_reason: "El secreto de la piel perfecta, directamente de Corea del Sur.",
        created_at: new Date("2026-01-06"),
    },
    {
        id: "11",
        title: "Experiencia de cata de vinos en La Rioja",
        description: "Visita a bodega, cata de 4 vinos premium y maridaje con productos locales.",
        price: 89.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=500",
        source_url: "https://amazon.es/dp/B0WINE123",
        platform: "amazon",
        category: "travel-experiences",
        findly_reason: "Una experiencia inolvidable para los amantes del buen vino.",
        created_at: new Date("2026-01-05"),
    },
    {
        id: "12",
        title: "Smartwatch Samsung Galaxy Watch 6",
        description: "Monitorización de salud, GPS integrado y batería de larga duración.",
        price: 319.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500",
        source_url: "https://amazon.es/dp/B0WATCH456",
        platform: "amazon",
        category: "tech-electronics",
        findly_reason: "Tecnología de vanguardia para un estilo de vida conectado y saludable.",
        created_at: new Date("2026-01-04"),
    },
    {
        id: "13",
        title: "Bufanda de cachemira 100%",
        description: "Cachemira pura de Mongolia, suavidad extrema y calidez incomparable.",
        price: 125.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=500",
        source_url: "https://elcorteingles.es/moda/bufanda-cachemira",
        platform: "elcorteingles",
        category: "fashion",
        findly_reason: "Un lujo accesible que abriga el cuerpo y el corazón.",
        created_at: new Date("2026-01-03"),
    },
    {
        id: "14",
        title: "Bicicleta de montaña Rockrider",
        description: "Marco de aluminio, 21 velocidades, frenos de disco hidráulicos.",
        price: 399.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=500",
        source_url: "https://decathlon.es/bicicleta-montana",
        platform: "decathlon",
        category: "sports-outdoors",
        findly_reason: "Para quien busca aventura y libertad en cada pedaleo.",
        created_at: new Date("2026-01-02"),
    },
    {
        id: "15",
        title: "Vinilo tocadiscos vintage restaurado",
        description: "Tocadiscos de los años 70, completamente restaurado y funcionando perfectamente.",
        price: 199.00,
        currency: "EUR",
        image_url: "https://images.unsplash.com/photo-1539185441755-769473a23570?w=500",
        source_url: "https://etsy.com/listing/345678",
        platform: "etsy",
        category: "music",
        findly_reason: "El sonido auténtico del vinilo para los verdaderos melómanos.",
        created_at: new Date("2026-01-01"),
    },
];
